import { NextResponse } from "next/server";
import { createJob, ensureRemote, getJob, listFailedTransferFiles, listTransferFiles, queueTransferFiles, updateJob } from "@/lib/db";
import { refreshJob } from "@/lib/job-monitor";
import { rc, startTransfer } from "@/lib/rclone";
import { z } from "zod";

export async function GET(request: Request, {params}: {params: Promise<{id: string}>}) { try { const {id} = await params; const job = await refreshJob(Number(id)); const query = new URL(request.url).searchParams; const requestedState = query.get("state"); const state = requestedState === "finished" || requestedState === "failed" ? requestedState : "transferring"; const page = Math.max(1, Number(query.get("page")) || 1); return NextResponse.json({...job, ...listTransferFiles(Number(id), state, page, 100, query.get("search") || "")}); } catch (error) { return NextResponse.json({error: error instanceof Error ? error.message : String(error)}, {status: 502}); } }
export async function POST(request: Request, {params}: {params: Promise<{id: string}>}) { try { const {id} = await params; const job = getJob(Number(id)); if (!job) throw new Error("未找到任务记录"); const {fileIds} = z.object({fileIds: z.array(z.number().int().positive()).min(1).optional()}).parse(await request.json()); const files = listFailedTransferFiles(job.id, fileIds); if (!files.length) throw new Error("没有可重试的失败文件"); const statsGroup = `sync-${crypto.randomUUID()}`; const result = await startTransfer(job.operation, job.source, job.destination, statsGroup, files.map((file) => file.path)); const remoteId = ensureRemote(job.source.split(":", 1)[0]).id; const retry = createJob({name: `${job.name}（重试）`, remoteId, operation: job.operation, source: job.source, destination: job.destination, statsGroup, rcloneJobId: result.jobid}); queueTransferFiles(retry.id, files.map(({path, size}) => ({path, size}))); return NextResponse.json(retry, {status: 201}); } catch (error) { return NextResponse.json({error: error instanceof Error ? error.message : String(error)}, {status: 400}); } }
export async function DELETE(_: Request, {params}: {params: Promise<{id: string}>}) { try { const {id} = await params; const job = getJob(Number(id)); if (!job?.rcloneJobId || job.status !== "running") throw new Error("任务不可取消"); await rc("job/stop", {jobid: job.rcloneJobId}); updateJob(job.id, {status: "cancelled", finishedAt: new Date().toISOString()}); return NextResponse.json({ok: true}); } catch (error) { return NextResponse.json({error: error instanceof Error ? error.message : String(error)}, {status: 400}); } }
