import Database from "better-sqlite3";
import path from "node:path";
import fs from "node:fs";
import type { Remote, SyncJob, TransferFile, TransferStats } from "./types";

const file = process.env.DATABASE_PATH || "./data/rclone.sqlite";
fs.mkdirSync(path.dirname(path.resolve(file)), {recursive: true});
const db = new Database(path.resolve(file));
db.pragma("journal_mode = WAL");
db.exec(`CREATE TABLE IF NOT EXISTS remotes (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, type TEXT NOT NULL, config TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS jobs (id INTEGER PRIMARY KEY AUTOINCREMENT, remote_id INTEGER, name TEXT, operation TEXT NOT NULL, source TEXT NOT NULL, destination TEXT NOT NULL, status TEXT NOT NULL, rclone_job_id INTEGER, stats_group TEXT, stats TEXT, error TEXT, created_at TEXT NOT NULL, finished_at TEXT);
CREATE TABLE IF NOT EXISTS transfer_files (id INTEGER PRIMARY KEY AUTOINCREMENT, job_id INTEGER NOT NULL, path TEXT NOT NULL, size INTEGER NOT NULL DEFAULT 0, bytes INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL, error TEXT, started_at TEXT NOT NULL, finished_at TEXT, UNIQUE(job_id, path));
CREATE TABLE IF NOT EXISTS schedules (id INTEGER PRIMARY KEY AUTOINCREMENT, remote_id INTEGER NOT NULL, operation TEXT NOT NULL, source TEXT NOT NULL, destination TEXT NOT NULL, cron TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1);`);
for (const statement of ["ALTER TABLE jobs ADD COLUMN name TEXT", "ALTER TABLE jobs ADD COLUMN stats_group TEXT"]) { try { db.exec(statement); } catch {} }

function mapJob(row: any): SyncJob { return {...row, remoteId: row.remote_id, remoteName: row.remoteName, rcloneJobId: row.rclone_job_id || undefined, statsGroup: row.stats_group || `job-${row.id}`, stats: row.stats ? JSON.parse(row.stats) : undefined, createdAt: row.created_at, finishedAt: row.finished_at}; }
export function listRemotes(): Remote[] { return db.prepare("SELECT id,name,type,config,created_at createdAt FROM remotes ORDER BY id DESC").all().map((r: any) => ({...r, config: JSON.parse(r.config)})) as Remote[]; }
export function createRemote(data: Omit<Remote,"id"|"createdAt">) { const now = new Date().toISOString(); const result = db.prepare("INSERT INTO remotes (name,type,config,created_at) VALUES (?,?,?,?)").run(data.name,data.type,JSON.stringify(data.config),now); return {id:Number(result.lastInsertRowid),...data,createdAt:now}; }
export function ensureRemote(name: string, type = "unknown") { const existing = db.prepare("SELECT id,name,type,config,created_at createdAt FROM remotes WHERE name=?").get(name) as any; return existing ? {...existing,config:JSON.parse(existing.config)} as Remote : createRemote({name,type,config:{}}); }
export function updateRemote(id: number, data: Pick<Remote, "type" | "config">) { db.prepare("UPDATE remotes SET type=?,config=? WHERE id=?").run(data.type, JSON.stringify(data.config), id); return getRemote(id); }
export function getRemote(id:number): Remote | undefined { const r:any=db.prepare("SELECT id,name,type,config,created_at createdAt FROM remotes WHERE id=?").get(id); return r&&({...r,config:JSON.parse(r.config)}); }
export function listJobs(): SyncJob[] { return db.prepare("SELECT j.*, r.name remoteName FROM jobs j LEFT JOIN remotes r ON r.id=j.remote_id ORDER BY j.id DESC").all().map(mapJob); }
export function getJob(id: number): SyncJob | undefined { const row = db.prepare("SELECT j.*, r.name remoteName FROM jobs j LEFT JOIN remotes r ON r.id=j.remote_id WHERE j.id=?").get(id); return row ? mapJob(row) : undefined; }
export function createJob(data: {name:string;remoteId?:number;operation:"sync"|"copy";source:string;destination:string;statsGroup:string;rcloneJobId?:number}) { const now=new Date().toISOString(); const result=db.prepare("INSERT INTO jobs (remote_id,name,operation,source,destination,status,rclone_job_id,stats_group,created_at) VALUES (?,?,?,?,?,?,?,?,?)").run(data.remoteId || null,data.name,data.operation,data.source,data.destination,"running",data.rcloneJobId || null,data.statsGroup,now); return getJob(Number(result.lastInsertRowid))!; }
export function updateJob(id:number, patch:{status?:string;stats?:TransferStats;error?:string;finishedAt?:string}) { db.prepare("UPDATE jobs SET status=COALESCE(?,status),stats=COALESCE(?,stats),error=COALESCE(?,error),finished_at=COALESCE(?,finished_at) WHERE id=?").run(patch.status || null,patch.stats ? JSON.stringify(patch.stats) : null,patch.error || null,patch.finishedAt || null,id); return getJob(id); }
export function upsertTransferFile(data: Omit<TransferFile,"id">) { db.prepare("INSERT INTO transfer_files (job_id,path,size,bytes,status,error,started_at,finished_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(job_id,path) DO UPDATE SET size=excluded.size,bytes=excluded.bytes,status=excluded.status,error=excluded.error,finished_at=excluded.finished_at").run(data.jobId,data.path,data.size,data.bytes,data.status,data.error || null,data.startedAt,data.finishedAt || null); }
export function listTransferFiles(jobId: number, state?: "transferring" | "finished", page = 1, pageSize = 10) { const where = state === "transferring" ? "AND status='transferring'" : state === "finished" ? "AND status!='transferring'" : ""; const total = (db.prepare(`SELECT COUNT(*) count FROM transfer_files WHERE job_id=? ${where}`).get(jobId) as {count:number}).count; const counts = db.prepare("SELECT SUM(CASE WHEN status='transferring' THEN 1 ELSE 0 END) transferring, SUM(CASE WHEN status!='transferring' THEN 1 ELSE 0 END) finished FROM transfer_files WHERE job_id=?").get(jobId) as {transferring:number | null;finished:number | null}; const files = db.prepare(`SELECT id,job_id jobId,path,size,bytes,status,error,started_at startedAt,finished_at finishedAt FROM transfer_files WHERE job_id=? ${where} ORDER BY CASE status WHEN 'transferring' THEN 0 WHEN 'failed' THEN 1 ELSE 2 END, id DESC LIMIT ? OFFSET ?`).all(jobId,pageSize,(page - 1) * pageSize) as TransferFile[]; return {files,total,page,pageSize,counts:{transferring:counts.transferring || 0,finished:counts.finished || 0}}; }
export function listSchedules(){return db.prepare("SELECT * FROM schedules WHERE enabled=1").all();}
export function createSchedule(data:{remoteId:number;operation:string;source:string;destination:string;cron:string}){return db.prepare("INSERT INTO schedules (remote_id,operation,source,destination,cron) VALUES (?,?,?,?,?)").run(data.remoteId,data.operation,data.source,data.destination,data.cron);}
